// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAR_0KjgAc3ow2SEclQooPH0RV2BVxbrA',
    appId: '1:346283658022:web:8121717ee774d01f680fe7',
    messagingSenderId: '346283658022',
    projectId: 'multipleloginfirebase',
    authDomain: 'multipleloginfirebase.firebaseapp.com',
    databaseURL: 'https://multipleloginfirebase.firebaseio.com',
    storageBucket: 'multipleloginfirebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwvNx9_4eW7QlOO1r5HptPEjog_kXOrUA',
    appId: '1:346283658022:android:9c7fe9cc06fa40a7680fe7',
    messagingSenderId: '346283658022',
    projectId: 'multipleloginfirebase',
    databaseURL: 'https://multipleloginfirebase.firebaseio.com',
    storageBucket: 'multipleloginfirebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALg4OEoF9DUtk_GnFCGf7dOKdQoqjR9lY',
    appId: '1:346283658022:ios:cc08e8ee3bbb6bd3680fe7',
    messagingSenderId: '346283658022',
    projectId: 'multipleloginfirebase',
    databaseURL: 'https://multipleloginfirebase.firebaseio.com',
    storageBucket: 'multipleloginfirebase.appspot.com',
    androidClientId: '346283658022-jbv9oe6c9a1i8qc4icnqv35bogfbbg55.apps.googleusercontent.com',
    iosClientId: '346283658022-3j4vj6aj31gau27rqn487a6ujduimssg.apps.googleusercontent.com',
    iosBundleId: 'com.example.androidFbFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALg4OEoF9DUtk_GnFCGf7dOKdQoqjR9lY',
    appId: '1:346283658022:ios:cc08e8ee3bbb6bd3680fe7',
    messagingSenderId: '346283658022',
    projectId: 'multipleloginfirebase',
    databaseURL: 'https://multipleloginfirebase.firebaseio.com',
    storageBucket: 'multipleloginfirebase.appspot.com',
    androidClientId: '346283658022-jbv9oe6c9a1i8qc4icnqv35bogfbbg55.apps.googleusercontent.com',
    iosClientId: '346283658022-3j4vj6aj31gau27rqn487a6ujduimssg.apps.googleusercontent.com',
    iosBundleId: 'com.example.androidFbFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAR_0KjgAc3ow2SEclQooPH0RV2BVxbrA',
    appId: '1:346283658022:web:6bc96de081364f39680fe7',
    messagingSenderId: '346283658022',
    projectId: 'multipleloginfirebase',
    authDomain: 'multipleloginfirebase.firebaseapp.com',
    databaseURL: 'https://multipleloginfirebase.firebaseio.com',
    storageBucket: 'multipleloginfirebase.appspot.com',
  );
}
